// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PodSetListerExpansion allows custom methods to be added to
// PodSetLister.
type PodSetListerExpansion interface{}

// PodSetNamespaceListerExpansion allows custom methods to be added to
// PodSetNamespaceLister.
type PodSetNamespaceListerExpansion interface{}
