// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	demov1alpha1 "github.com/hrishin/podset-operator/pkg/apis/demo/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodSetLister helps list PodSets.
// All objects returned here must be treated as read-only.
type PodSetLister interface {
	// List lists all PodSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*demov1alpha1.PodSet, err error)
	// PodSets returns an object that can list and get PodSets.
	PodSets(namespace string) PodSetNamespaceLister
	PodSetListerExpansion
}

// podSetLister implements the PodSetLister interface.
type podSetLister struct {
	listers.ResourceIndexer[*demov1alpha1.PodSet]
}

// NewPodSetLister returns a new PodSetLister.
func NewPodSetLister(indexer cache.Indexer) PodSetLister {
	return &podSetLister{listers.New[*demov1alpha1.PodSet](indexer, demov1alpha1.Resource("podset"))}
}

// PodSets returns an object that can list and get PodSets.
func (s *podSetLister) PodSets(namespace string) PodSetNamespaceLister {
	return podSetNamespaceLister{listers.NewNamespaced[*demov1alpha1.PodSet](s.ResourceIndexer, namespace)}
}

// PodSetNamespaceLister helps list and get PodSets.
// All objects returned here must be treated as read-only.
type PodSetNamespaceLister interface {
	// List lists all PodSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*demov1alpha1.PodSet, err error)
	// Get retrieves the PodSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*demov1alpha1.PodSet, error)
	PodSetNamespaceListerExpansion
}

// podSetNamespaceLister implements the PodSetNamespaceLister
// interface.
type podSetNamespaceLister struct {
	listers.ResourceIndexer[*demov1alpha1.PodSet]
}
