// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hrishin/podset-operator/pkg/apis/demo/v1alpha1"
	demov1alpha1 "github.com/hrishin/podset-operator/pkg/client/clientset/versioned/typed/demo/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePodSets implements PodSetInterface
type fakePodSets struct {
	*gentype.FakeClientWithList[*v1alpha1.PodSet, *v1alpha1.PodSetList]
	Fake *FakeDemoV1alpha1
}

func newFakePodSets(fake *FakeDemoV1alpha1, namespace string) demov1alpha1.PodSetInterface {
	return &fakePodSets{
		gentype.NewFakeClientWithList[*v1alpha1.PodSet, *v1alpha1.PodSetList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("podsets"),
			v1alpha1.SchemeGroupVersion.WithKind("PodSet"),
			func() *v1alpha1.PodSet { return &v1alpha1.PodSet{} },
			func() *v1alpha1.PodSetList { return &v1alpha1.PodSetList{} },
			func(dst, src *v1alpha1.PodSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PodSetList) []*v1alpha1.PodSet { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.PodSetList, items []*v1alpha1.PodSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
