// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apisdemov1alpha1 "github.com/hrishin/podset-operator/pkg/apis/demo/v1alpha1"
	versioned "github.com/hrishin/podset-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/hrishin/podset-operator/pkg/client/informers/externalversions/internalinterfaces"
	demov1alpha1 "github.com/hrishin/podset-operator/pkg/client/listers/demo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodSetInformer provides access to a shared informer and lister for
// PodSets.
type PodSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() demov1alpha1.PodSetLister
}

type podSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodSetInformer constructs a new informer for PodSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodSetInformer constructs a new informer for PodSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().PodSets(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().PodSets(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().PodSets(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().PodSets(namespace).Watch(ctx, options)
			},
		}, client),
		&apisdemov1alpha1.PodSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *podSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisdemov1alpha1.PodSet{}, f.defaultInformer)
}

func (f *podSetInformer) Lister() demov1alpha1.PodSetLister {
	return demov1alpha1.NewPodSetLister(f.Informer().GetIndexer())
}
