/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	demov1alpha1 "github.com/hrishin/podset-operator/pkg/apis/demo/v1alpha1"
	versioned "github.com/hrishin/podset-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/hrishin/podset-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/hrishin/podset-operator/pkg/client/listers/demo/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PodSetInformer provides access to a shared informer and lister for
// PodSets.
type PodSetInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PodSetLister
}

type podSetInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPodSetInformer constructs a new informer for PodSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPodSetInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPodSetInformer constructs a new informer for PodSet type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodSetInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().PodSets(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DemoV1alpha1().PodSets(namespace).Watch(options)
			},
		},
		&demov1alpha1.PodSet{},
		resyncPeriod,
		indexers,
	)
}

func (f *podSetInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPodSetInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *podSetInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&demov1alpha1.PodSet{}, f.defaultInformer)
}

func (f *podSetInformer) Lister() v1alpha1.PodSetLister {
	return v1alpha1.NewPodSetLister(f.Informer().GetIndexer())
}
