// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	demov1alpha1 "github.com/hrishin/podset-operator/pkg/apis/demo/v1alpha1"
	scheme "github.com/hrishin/podset-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PodSetsGetter has a method to return a PodSetInterface.
// A group's client should implement this interface.
type PodSetsGetter interface {
	PodSets(namespace string) PodSetInterface
}

// PodSetInterface has methods to work with PodSet resources.
type PodSetInterface interface {
	Create(ctx context.Context, podSet *demov1alpha1.PodSet, opts v1.CreateOptions) (*demov1alpha1.PodSet, error)
	Update(ctx context.Context, podSet *demov1alpha1.PodSet, opts v1.UpdateOptions) (*demov1alpha1.PodSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, podSet *demov1alpha1.PodSet, opts v1.UpdateOptions) (*demov1alpha1.PodSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*demov1alpha1.PodSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*demov1alpha1.PodSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *demov1alpha1.PodSet, err error)
	PodSetExpansion
}

// podSets implements PodSetInterface
type podSets struct {
	*gentype.ClientWithList[*demov1alpha1.PodSet, *demov1alpha1.PodSetList]
}

// newPodSets returns a PodSets
func newPodSets(c *DemoV1alpha1Client, namespace string) *podSets {
	return &podSets{
		gentype.NewClientWithList[*demov1alpha1.PodSet, *demov1alpha1.PodSetList](
			"podsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *demov1alpha1.PodSet { return &demov1alpha1.PodSet{} },
			func() *demov1alpha1.PodSetList { return &demov1alpha1.PodSetList{} },
		),
	}
}
