/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/hrishin/podset-operator/pkg/apis/demo/v1alpha1"
	scheme "github.com/hrishin/podset-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PodSetsGetter has a method to return a PodSetInterface.
// A group's client should implement this interface.
type PodSetsGetter interface {
	PodSets(namespace string) PodSetInterface
}

// PodSetInterface has methods to work with PodSet resources.
type PodSetInterface interface {
	Create(*v1alpha1.PodSet) (*v1alpha1.PodSet, error)
	Update(*v1alpha1.PodSet) (*v1alpha1.PodSet, error)
	UpdateStatus(*v1alpha1.PodSet) (*v1alpha1.PodSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PodSet, error)
	List(opts v1.ListOptions) (*v1alpha1.PodSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodSet, err error)
	PodSetExpansion
}

// podSets implements PodSetInterface
type podSets struct {
	client rest.Interface
	ns     string
}

// newPodSets returns a PodSets
func newPodSets(c *DemoV1alpha1Client, namespace string) *podSets {
	return &podSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the podSet, and returns the corresponding podSet object, and an error if there is any.
func (c *podSets) Get(name string, options v1.GetOptions) (result *v1alpha1.PodSet, err error) {
	result = &v1alpha1.PodSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podsets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PodSets that match those selectors.
func (c *podSets) List(opts v1.ListOptions) (result *v1alpha1.PodSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PodSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("podsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested podSets.
func (c *podSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("podsets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a podSet and creates it.  Returns the server's representation of the podSet, and an error, if there is any.
func (c *podSets) Create(podSet *v1alpha1.PodSet) (result *v1alpha1.PodSet, err error) {
	result = &v1alpha1.PodSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("podsets").
		Body(podSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a podSet and updates it. Returns the server's representation of the podSet, and an error, if there is any.
func (c *podSets) Update(podSet *v1alpha1.PodSet) (result *v1alpha1.PodSet, err error) {
	result = &v1alpha1.PodSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podsets").
		Name(podSet.Name).
		Body(podSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *podSets) UpdateStatus(podSet *v1alpha1.PodSet) (result *v1alpha1.PodSet, err error) {
	result = &v1alpha1.PodSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("podsets").
		Name(podSet.Name).
		SubResource("status").
		Body(podSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the podSet and deletes it. Returns an error if one occurs.
func (c *podSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podsets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *podSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("podsets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched podSet.
func (c *podSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PodSet, err error) {
	result = &v1alpha1.PodSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("podsets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
